<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.3.0.0</Version>
    <PackageProjectUrl>https://github.com/Yesanith/RegionsOfXIV</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="RegionsOfXIV.Tests" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' != 'Debug'">
    <Compile Remove="Services\AddonNodeDump.cs" />
    <Compile Remove="Services\SheetSearch.cs" />
    <Compile Remove="UI\IconBrowserWindow.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\assets\fonts\**\*.ttf;..\..\assets\fonts\**\*.otf">
      <Link>Fonts\%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>

    <Content Include="..\..\assets\images\icon.png">
      <Link>images\icon.png</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>
  </ItemGroup>
</Project>
